"""

"""
# def start_dijkstra(self, source_id):
#     """ Finding distance from source to other vertices using Dijkstra algorithm
#     :Input:
#         source: The starting vertex

#     :Post condition: All vertices in the graph will have their closest distance from source
#     """
#     # Starting vertex and initialising MinHeap and returning list
#     source = self.vertices[source_id]
#     source.inDist = 0
#     source.discovered = True

#     dijk_minheap = MinHeap(len(self.vertices))

#     # Resetting all vertices
#     for vert in self.vertices:
#         if vert.id != source_id:
#             vert.inDist = INFINITY
#             vert.discovered = False
#             vert.visited = False
#         dijk_minheap.append(vert)

#     # Traversing the entire graph
#     while len(dijk_minheap) > 0:
#         u = dijk_minheap.serve()
#         u.visited = True

#         # Going through all edges of u
#         for edge in u.edges:
#             v = edge.v
#             new_dist = u.inDist + edge.w

#             # Add neighbouring vertices to discovered if not in already
#             if not v.discovered:
#                 v.discovered = True

#                 # Updating distance and previous vertex
#                 v.inDist, v.previous = new_dist, u
#                 dijk_minheap.update(v)

#             # Not visited = not finalised
#             elif not v.visited and v.distance > new_dist:
#                 # Updating distance and previous vertex
#                 v.inDist, v.previous = new_dist, u
#                 dijk_minheap.update(v)

# def out_dijkstra(self, source_id):
#     """ Finding distance from source to other vertices using Dijkstra algorithm
#     :Input:
#         source: The starting vertex

#     :Post condition: All vertices in the graph will have their closest distance from source
#     """
#     # Starting vertex and initialising MinHeap and returning list
#     source = self.vertices[source_id]
#     source.outDist = 0
#     source.discovered = True

#     dijk_minheap = MinHeap(len(self.vertices))

#     # Resetting all vertices
#     for vert in self.vertices:
#         if vert.id != source_id:
#             vert.outDist = INFINITY
#             vert.discovered = False
#             vert.visited = False
#         dijk_minheap.append(vert)

#     # Traversing the entire graph
#     while len(dijk_minheap) > 0:
#         u = dijk_minheap.serve()
#         u.visited = True

#         # Going through all edges of u
#         for edge in u.edges:
#             v = edge.v
#             new_dist = u.outDist + edge.w

#             # Add neighbouring vertices to discovered if not in already
#             if not v.discovered:
#                 v.discovered = True

#                 # Updating distance and previous vertex
#                 v.outDist, v.previous = new_dist, u
#                 dijk_minheap.update(v)

#             # Not visited = not finalised
#             elif not v.visited and v.distance > new_dist:
#                 # Updating distance and previous vertex
#                 v.outDist, v.previous = new_dist, u
#                 dijk_minheap.update(v)

import random


with open("prefix-file", "r") as f:
    lines = [line.strip() for line in f]
    lines.sort()
    prefix_regex = '|'.join(lines)

with open("middle-file", "r") as f:
    lines = [line.strip() for line in f]
    lines.sort()
    middle_regex = '|'.join(lines)

with open("suffix-file", "r") as f:
    lines = [line.strip() for line in f]
    lines.sort()
    suffix_regex = '|'.join(lines)

# print(prefix_regex)
# print(middle_regex)
# print(suffix_regex)


def create_results():

    def completed(partial):
        return len(partial) == 3

    def solution(partial=''):
        if completed(partial):
            return [partial]

        res = []
        options = ['A', 'B', 'C']
        for o in options:
            res += solution(partial + o)

        return res

    return solution()


score = 100
# team1 = create_results()
# team2 = create_results()
# results = []
# for teamx in team1:
#     for teamy in team2:
#         results.append([teamx, teamy, score])
#         score -= 1
# print(results)

results = [['AAA', 'AAA', 100], ['AAA', 'AAB', 99], ['AAA', 'ABA', 98], ['AAA', 'ABB', 97],
           ['AAA', 'BAA', 96], ['AAA', 'BAB', 95], [
               'AAA', 'BBA', 94], ['AAA', 'BBB', 93],
           ['AAB', 'AAA', 92], ['AAB', 'AAB', 91], [
               'AAB', 'ABA', 90], ['AAB', 'ABB', 89],
           ['AAB', 'BAA', 88], ['AAB', 'BAB', 87], [
    'AAB', 'BBA', 86], ['AAB', 'BBB', 85],
    ['ABA', 'AAA', 84], ['ABA', 'AAB', 83], [
        'ABA', 'ABA', 82], ['ABA', 'ABB', 81],
    ['ABA', 'BAA', 80], ['ABA', 'BAB', 79], [
        'ABA', 'BBA', 78], ['ABA', 'BBB', 77],
    ['ABB', 'AAA', 76], ['ABB', 'AAB', 75], [
        'ABB', 'ABA', 74], ['ABB', 'ABB', 73],
    ['ABB', 'BAA', 72], ['ABB', 'BAB', 71], [
        'ABB', 'BBA', 70], ['ABB', 'BBB', 69],
    ['BAA', 'AAA', 68], ['BAA', 'AAB', 67], [
        'BAA', 'ABA', 66], ['BAA', 'ABB', 65],
    ['BAA', 'BAA', 64], ['BAA', 'BAB', 63], [
        'BAA', 'BBA', 62], ['BAA', 'BBB', 61],
    ['BAB', 'AAA', 60], ['BAB', 'AAB', 59], [
        'BAB', 'ABA', 58], ['BAB', 'ABB', 57],
    ['BAB', 'BAA', 56], ['BAB', 'BAB', 55], [
        'BAB', 'BBA', 54], ['BAB', 'BBB', 53],
    ['BBA', 'AAA', 52], ['BBA', 'AAB', 51], [
        'BBA', 'ABA', 50], ['BBA', 'ABB', 49],
    ['BBA', 'BAA', 48], ['BBA', 'BAB', 47], [
        'BBA', 'BBA', 46], ['BBA', 'BBB', 45],
    ['BBB', 'AAA', 44], ['BBB', 'AAB', 43], [
        'BBB', 'ABA', 42], ['BBB', 'ABB', 41],
    ['BBB', 'BAA', 40], ['BBB', 'BAB', 39], ['BBB', 'BBA', 38], ['BBB', 'BBB', 37]]

# abc_teams = create_results()
# print(abc_teams)
# for i in range(128):
# results
# visited = []
# for r in results:
#     if len(visited) == len(abc_teams):
#         break
#     x = random.randint(0, len(abc_teams) - 1)
#     while x in visited:
#         x = random.randint(0, len(abc_teams) - 1)
#     r[0] = abc_teams[x]
#     visited.append(x)

max_letter = ord('Z')
min_letter = ord('A')
max_score = 100
N = 300
M = 12
results = []
for _ in range(N):
    team1 = ''
    team2 = ''
    for i in range(M):
        team1 += chr(random.randint(min_letter, max_letter))
        team2 += chr(random.randint(min_letter, max_letter))
    results.append([team1, team2, random.randint(0, max_score)])

results = \
[['ZVJUKWHPNIQO', 'BRJCVKEMTRKU', 63], ['YIQJXUCATBIY', 'GOEBKTNEQOXU', 39], ['MHUVYBQSAQLC', 'NTNKUQYWYMIV', 58], ['YTVHOGSGFHQK', 'KLDMPPXWRVXK', 39], ['QYJZIZLVZBJR', 'HHRFSLDRCYBR', 66], 
['NABGULQKKPSC', 'MYARMIMWUPQI', 33], ['MQEFHYWEQEQF', 'SKWTRINZKNHZ', 56], ['CFVLWYEPIHTD', 'VNVMOTETFNZS', 97], ['LUYFGOTQDNUW', 'LNOTZYAMBJDY', 15], ['AXLIHDJFQCND', 'SKAHGGPLJQDW', 26], 
['XBAAGNTXAIKR', 'THCSSZBZUENU', 77], ['CHRKLIGSILMJ', 'DAIZUYKLLWRF', 48], ['SOXUJJGBOMOL', 'GMPUWAUQISEV', 74], ['BPYNVMYYQQRC', 'ALOAEDBOCYKS', 76], ['NFLVFKOJSKRO', 'LXOJVBXVZOZK', 16], 
['PPVCXTPBMAEL', 'ZHFMTHBQFHXS', 76], ['ZKGHDFGCWFRG', 'SUTCSDSIFJTK', 88], ['OYVFIGWMZOWI', 'YGECHBKNYUWR', 44], ['KNXDGJJMKKPA', 'NGWWWPFNVXQM', 74], ['GABAUOHHKISI', 'WQCTSYPTQOAO', 46], 
['MWYGNZAZUGKW', 'HICKBOFGUBBU', 81], ['IPLPYFHHDKCQ', 'YILGAMWIXWLS', 29], ['FKYXDSJIWQWX', 'XGOSDDUZJRAX', 8], ['PTICQYGEBHIH', 'WNXOHQMVOFSQ', 51], ['SVTGRKABFLVT', 'YQDMWUHWPTQW', 24], 
['IRMMHZESILHY', 'HISSLSKXZQYI', 51], ['HLPQTTWPZQHH', 'LNWBQTBBXFYR', 47], ['BZMCBVIQMTRD', 'RXOFFOLYCNCW', 94], ['MHVWDCDUYNDG', 'PPUZPAUKVECW', 47], ['NCKGDMIOUCFA', 'AUEKROBRPTOS', 59], 
['WNBNPIVCHGMR', 'ENLHLBAAYOJY', 93], ['WMKTQJWKKFDX', 'IIFOLFTGDCBP', 78], ['OIWAFYULUVBA', 'PPXMNMDOHQJY', 29], ['BGPZBTDUEVLY', 'BJZACXREPIEP', 79], ['QZHDRHLREVZF', 'YTQKJWOMDSBK', 0], 
['YFHFNWUMQTXO', 'JUIIRSDRKZVG', 64], ['YTBJVGNBIANK', 'ZZWGRLMLTFQK', 6], ['FJZKABDMBXQR', 'XWHMHSEWPVUI', 9], ['RLTMZFUMVPFD', 'SAPFUDVUXMWN', 12], ['RBFMNUDAFXQT', 'RSFCBRKAAXTK', 60], 
['DFDZJAYUBNIY', 'QAKYJQNDVSFJ', 0], ['AIUDHAIJMOUZ', 'NVEFIMYYMGYK', 19], ['JKNOADVQUTZY', 'AMDZPGUVRXAO', 14], ['RWZGJXAGRZIB', 'FHXYNYLTPCDJ', 21], ['RIMHNHUDCHYE', 'YVFOYMXOMPWL', 70], 
['OTDPYQXTRZPY', 'LGECGEVJRRCB', 11], ['NACUFYQRJKBG', 'XVWKPSNJJFIM', 95], ['FDTBYTDUSOGQ', 'ZGKXDRSFIWLI', 32], ['BBFPVZINOPQH', 'DIJULBSCJMGR', 40], ['PBTBHRWXXADT', 'NRNIHRQDAHWD', 68], 
['LUVBIWYQDHUM', 'OMZKEPTSFFFT', 72], ['UBATNOWFHMNP', 'GNGHHBDMOMSS', 43], ['QAZVAHCKMBTT', 'KWIIUHIWYRLM', 45], ['AKJVIHICULQT', 'OUOMMNQYMQVL', 55], ['GTEKJMWYQTEG', 'HKYVMPNPNTOX', 3], 
['BXYSZCOUZAYK', 'RXGQIBOPRALN', 17], ['VZPSHAYQBAYJ', 'DAZENTPOGGLP', 91], ['EIPVUJZPSSWW', 'LLCAEBHPCIFM', 18], ['YHOBYPDCVDRF', 'IZDKIUXPZYAF', 90], ['OTPWEYCKGWCF', 'ZPRLOMKQEFIH', 52], 
['OSPAVMUOOHCC', 'CYKDYDZNFBSY', 51], ['RWQSGDJSXABZ', 'PRYRYLWEVLPA', 13], ['YTDIZCYNYDMH', 'JRVZAPAJJAJR', 32], ['CDPZWKHBUJHN', 'VWLROBUEHZGZ', 67], ['KBWEVADGOVBJ', 'LJDEZUFSAXUX', 38], 
['IFRNHGUUCCVP', 'UQWVTEUMTRXJ', 55], ['NIXPFMTBOTQD', 'JHGONFJBUBRS', 19], ['TDVPBBEYIRUT', 'CJBVVHEKSMPN', 56], ['PKGUXCSPOJIY', 'RRZPXELGRUOY', 34], ['OCIQLOBFSBBV', 'ZDZDCDDKFJPI', 97], 
['ARZKETUFBBSJ', 'LPACWUGWHHXR', 14], ['VMCCGGFFCNHL', 'KDQKZCXEZXKV', 48], ['AFMZATESMICM', 'YRBBLDBRKIBG', 20], ['EXCIFGHIIIYW', 'TLATBFPWSUOY', 64], ['XMNYYPFSVXTV', 'TQUCEWLXSXPF', 36], 
['JOWOIHWLSBSU', 'OFPCBACEAFLZ', 91], ['XGJNWDAZNQBS', 'JLACETXZZFGC', 48], ['BOANPTJMQYSX', 'VHIZOYILVBQO', 74], ['VGYBNQECUPEO', 'RABRJTMZGBFZ', 40], ['OAYGMXISJXWN', 'FUXYIJEZIAOK', 81], 
['KDQXAPPLQLYH', 'AHNKYNEAGJAE', 5], ['EFXJEEAWXKFM', 'XMQLCIMRECNC', 53], ['TQRAWTGOWJAD', 'LEREHCJKZWOW', 37], ['PDMDWVNCRSET', 'PFORZIONAEGN', 86], ['EJSLEVABTAOW', 'TRERGQLWOTFV', 49], 
['JDSKXIVTLQZS', 'VSEUXFTKEUVE', 63], ['ZWCUCUFPOUFR', 'CXLUZQMJINCL', 65], ['JHYRUBTEHPED', 'RUWQCOFYAFUT', 91], ['MJFHURPYVOBI', 'ABYZRFGISGHP', 7], ['HYEWEUDNRVES', 'YXPIPIEMLPFK', 34], 
['FOTWRBBNMNAO', 'SRIPDFOAVPWN', 24], ['QUBPNNZYXDTC', 'EDWMRLJJSPWW', 51], ['ALFULLUZZOEZ', 'JSMOKLVIEMPM', 99], ['VGENYRDSSZAT', 'ZGWDOBDQZPEJ', 60], ['EQSRFRDPPHHX', 'FMRZAIKGCIRC', 20], 
['ZTQJIKNXWALY', 'ORFLBEOXGQJP', 40], ['ZJRPZWYURGHL', 'JLNQTCDOUXTR', 12], ['TIOLRGSUORMX', 'CVLUSNOWXISR', 84], ['JIDEXUNBJCGP', 'UOCAHXYEPOGG', 92], ['OLALVLCSFSOE', 'YZTLJJQOXLFY', 27], 
['PSEEIUELNNDT', 'JNHFOVHHTCUX', 93], ['XDZOGZVXUJTC', 'QGSCUBNUVVFT', 88], ['WYIMCWRCTCWH', 'AWIPZLCCEBCO', 26], ['MUYMPOAIIAWF', 'VUCVZMFXRNJD', 63], ['DRYASDRMEQIB', 'DVMVOQLZBRDN', 80], 
['XULOEINLHWCP', 'PAPQYCJROHQJ', 86], ['FTMOXXOFFHGL', 'ZFLTESOYUFJO', 16], ['USDEKGIOUXQM', 'YNCMEJTXOGUM', 49], ['RFSMPQGIMUEL', 'QIKNHJAOGIRS', 30], ['YIUQGDTHJNXD', 'JJILUWKIGDJT', 47], 
['IZUBECJNGOZB', 'JRZKKKOQZNXM', 64], ['AVKNGKGRHMPU', 'EKHFXQZJSOVG', 30], ['KOIEPBAUZYZB', 'XIDDPKYZVCHC', 82], ['QDZKPZWTCIHE', 'ILSCHPEGGFQT', 83], ['NNSEHTVORIKF', 'YPJIWWXHQIXE', 28], 
['JUQFMHNKTOXL', 'UQILUJDHRYVC', 25], ['LHZZWWIYJOQX', 'ZTXEQXPLZIIY', 82], ['MLHOCNBGZFPN', 'WSUKNZZVULEY', 75], ['IPRIJBWJNDLA', 'DLQPCMJGQOOJ', 38], ['WOKUNBQGBMZA', 'XQFWTTFUORFB', 43], 
['UGMWZVZAVVBS', 'WZVWEZXFFKXP', 12], ['MLDFTBNIOGYD', 'QQFSLOOOXKSN', 88], ['XCQKBAWZRKOF', 'IGBVSIXJHVEX', 44], ['QSEUPFOGOYSE', 'JQTDLAUVFLFA', 35], ['ZXDNYLCQPKKT', 'EOCNQEVWESMJ', 87], 
['YJFEXXCSRXCS', 'MXJKZBRWOWKF', 59], ['GDXQIVFTCCKO', 'EUZLCEOCBOWR', 20], ['NDSAEWFLAFXH', 'NJMSNTZVVGVQ', 75], ['UGLAJTODYOUO', 'DHOHAEBOCRZD', 91], ['XEXVTTIHKROW', 'LWGJMWICFYGF', 91], 
['JYDUTEPDRNCC', 'BQIQZRDVMPRU', 89], ['DRNTIKRELSHE', 'QRSYTIGRAINQ', 75], ['MALRDSBKORZG', 'QFVKPCFGVTPA', 26], ['PETLEOFDBZWH', 'FTRRUKQSCEOS', 27], ['VKNRYELHCUAG', 'PEVMRPGIOJOK', 20], 
['MZHLEZOJTUWQ', 'CIPFVXTRXAPH', 43], ['PJJKWPRCOEKI', 'XADTFXXHEKRI', 80], ['RHWURHROGOWY', 'XHQIVCBMNYVS', 96], ['XRANUHKYWXYE', 'TYYGMFWXUVCW', 80], ['TZHLYSADSXYR', 'YCKSMCXEDZJT', 56], 
['JWUGJCUYPMDY', 'OQRTKBPEEYZV', 44], ['HXEMIAWIWRFG', 'DXURSCEZQWEG', 75], ['ZXVCXJRCRYEW', 'DEEXOKUAQBCS', 79], ['DAGEKGVKUBSS', 'DORQRHMCFALM', 27], ['AOWNHNHVPAEV', 'PLORKAPBSHBO', 29], 
['OASCAWUDMPYU', 'CAYMUKJZZNHI', 17], ['INSNPQZRIVNF', 'HGIMUAABFQLL', 96], ['QXQZATGRXNRO', 'SNOVHLHPWHHI', 17], ['WQSCSAQFHZMC', 'XUYEPZEGYKVM', 85], ['VAZKGFMJLHVA', 'AFFPZQARTBXY', 25], 
['EXZKVFDJPSNW', 'TMODETZRFHSZ', 39], ['DKBAVHDSHYGP', 'LODBCMPVGWCO', 55], ['YSAYBCTQTJTI', 'AOTLCUDEQADK', 44], ['INLTVBNZFXRJ', 'RPOTFECPDQDD', 61], ['AHILJJIDTIDB', 'MHCQPHMCSSOZ', 77], 
['XUUDZKURKMKP', 'BMUATKHQUCCZ', 94], ['ATHVASPCLCNM', 'QZSGVKCRJCCM', 83], ['WMSEQIOLXAFF', 'LVKHUNSKZFLI', 34], ['OOPCXYPNPJGP', 'YWUMMTSSDDJO', 83], ['KAZZTFDIAZLV', 'UFBKUMAVSFDT', 64], 
['IADDKCJCLNVY', 'GDZHQZRZPHMG', 61], ['KEIDIFMUNPKU', 'DAZXEGUMLBRH', 54], ['IRZIQMFIQQTS', 'JYNGYRESTLDN', 33], ['VNDOEZQPAMPR', 'XUWVJPJRBZGT', 87], ['DKHUAKBFXVHW', 'PHZYCBWZLMQN', 91], 
['KBFXTXXTEZTJ', 'PFBUIZZZASSP', 24], ['QPPWLGBHWOZJ', 'YYBFQZOFUREF', 41], ['WJKOZGBFREDI', 'XCNZYKNTIKJX', 12], ['JBYKRECCKOTQ', 'TTADHSPCHGIC', 61], ['YZDCTAHATJIM', 'TLOMOPFGGGTL', 56], 
['QBKFDHRHREEC', 'FKGZFTZMKUHD', 20], ['PHCPBWKJCZSY', 'HTCKFHMBRISG', 54], ['VJUYETWQNZTU', 'ABOMMEYJJPDH', 29], ['BGRUTYSNBFMO', 'KSMYQWZNPKYF', 40], ['YVQQYQCUCPQF', 'PRXEJXRZBOXF', 22], 
['EZNKHWKAORVA', 'DOSMAUKTZANY', 97], ['JZKSPKZTSPHQ', 'SMPTXRCXKTUU', 92], ['EMDLPRWYDRFF', 'RHRTJNNHKUFY', 62], ['BDXGAKKBNIKP', 'LTSKARDJKEXM', 27], ['AQKDGWNWKQLI', 'FHGUSFDCCFRF', 60], 
['BKHUYGIWOOWK', 'HQOIGDLMNRMP', 70], ['XPUXMXPYCMAE', 'OTDYUKQESXMJ', 84], ['PVPBFDSSJJIW', 'NGQUFBJRSGDS', 23], ['KQWMRVTKVDKD', 'CREYZUNQGRDP', 14], ['MEBCNCWHFVLR', 'SQCFMQFOYBBG', 96], 
['VQMQHHBGCSPK', 'FBIPFKRACFZA', 62], ['RKTEZERYVOCV', 'MOGMHRDSVHHW', 66], ['NSOTWGHPXPZS', 'JXQOWYKVIUTU', 44], ['NEEQAVOGSPXL', 'DQSAKMCMCLXK', 47], ['GSTVFRZOTGZU', 'RNVZWJLJNUKX', 21], 
['RPALLVBJTXTP', 'ESTPLPLVZMZX', 62], ['ZDMWXVOFOQFU', 'XGBFTMXMZWWX', 12], ['QRISGPZADVPZ', 'ISIJEGJKVVEM', 64], ['LXUCXORRWWJF', 'BNUGSBZLJWUN', 24], ['PQNPFSNQFEZL', 'VOAMJAZQYVLM', 64], 
['XDPCTAJFYGOF', 'ALDCHSWOHEBO', 71], ['TYVLIQODJMWJ', 'RELFFIYRIYAO', 66], ['EXVXEONOPKCY', 'COPRUNMWCXIV', 0], ['EENOUAXSMYUW', 'EVFNDLFJTDXU', 40], ['DTZMYGMAREYS', 'GLCLSZUVLBAF', 37], 
['QGGPIZEVBVNY', 'KNFKEJQMHZKF', 2], ['QZCAINSSYWGH', 'MOMJLYDDGAWU', 47], ['PDYWQMRVTLAS', 'TJGGNJVQJRHY', 64], ['EVDLZUWFWRSJ', 'WDUFNRLEOFCO', 62], ['OMOCWGWYDFRF', 'PKUAMTMHMTUS', 26], 
['XHCFQWRXSABR', 'DIAQJWBGMXXA', 64], ['FWNFPYZXSKIC', 'TGVVVQAQLAFR', 14], ['YUYQBIHFIUPH', 'RCJZQCANMNUW', 41], ['CZHFAJJMFTRK', 'OEDRIRAEOQIO', 90], ['XFJBNEJMILXP', 'PPLOCJPZFUPO', 85], 
['ONJPZZWCJZMN', 'EROACCLBTFRT', 55], ['BWSPJPUXIDPJ', 'UIRFUUZCIKFS', 74], ['VNWNOCNHLKKZ', 'IXPCFZFWOYXK', 93], ['PMGSDDSTWWLF', 'FAELUNYMJBSQ', 44], ['VRKNNQCCNFZJ', 'RSIJMRLTVPPE', 42], 
['RYVJGEQJXYGN', 'QJWXNJNBLZYM', 79], ['WLEOAQHSIOOD', 'LEWJRPLLGUST', 68], ['VBTQXEPWPQRH', 'JCDGHAWUHMXM', 22], ['FWCDQIBPTNVT', 'AMMYXKCLVEDK', 42], ['PRYIUYGUOOJW', 'KVRKUMLTSIVK', 65], 
['DTIXJVKCMSUO', 'ATOHXUZTQJVC', 44], ['AEHMIBTJALBY', 'BTPOPXBLCUQG', 83], ['UUULFVDLTOTQ', 'KJAAJBPNDYWO', 21], ['SUSAWWEQCTZO', 'GSDQVWBAHESZ', 56], ['EEKFAHRPAJWV', 'MWCPISRXTUXQ', 92], 
['PJGGGANUJUUS', 'VHPCHCKOJLZM', 82], ['LPALKRMGZHNV', 'UVOFJMHGHDZW', 77], ['DGWINEOBFQEY', 'RXWNSTZDULIK', 95], ['XKRWJFWRKJLK', 'SWOARSWGNYOD', 9], ['JGAZTICEQXRQ', 'AZUFYWQLDUTI', 3], 
['GOJQESZSQOTL', 'BVKUZVMZOWNW', 80], ['YRWIGZHBEOXU', 'JGCURNPNQYUL', 37], ['VUXKHVIDSSHM', 'ZCBVRHAEYBYO', 37], ['RFTCNHTLJPTQ', 'FRPOUKZSPFML', 42], ['CQSUDPPCXZBS', 'EGQKQTYHQLPU', 61], 
['ZKAIWRMITYDK', 'YBPMZNUTTRSB', 41], ['VLKVYMAJJXNW', 'QXXNYZENZBSI', 12], ['XAJVPBEMJKIE', 'WNUOESCDBOFH', 46], ['MOPXQDNCQLJN', 'EFGPOOEIUYWI', 76], ['CDZAYGSUGLSF', 'RJNONOJLGWTE', 23], 
['SVDVVNUEGFZO', 'JKTKAYKCZEJV', 59], ['BPVZEYAYTCND', 'VSSTIKPKJGWA', 88], ['UIJWHIRZJJPH', 'FDZROLKLUUTU', 1], ['JEJWUUDSRDYB', 'WLOYXLSMWWWP', 82], ['XJKLUFLNJHMB', 'SEJHHADSFCAV', 35], 
['TNAUMQXVAIKG', 'NJHHECVUFSXP', 5], ['TEXQZHMRIBJJ', 'LTIKLHFCIYDG', 70], ['IFWDVELUZJPT', 'TKMJDTHNUUMV', 16], ['JSWSVFIMEGJD', 'NEVAWFETYEPX', 1], ['TYETFFHVMSRH', 'ZNPUIMFMJFOQ', 96], 
['CYESZGQGULJX', 'OLYURDBNRLZN', 10], ['QQSEBLMUDMMY', 'AIFQGZSPVHFS', 87], ['AKIVOQRVWWHC', 'MGUAFANTFGXO', 96], ['UJYXUCKMLSPE', 'CVSZAWBZGJOE', 73], ['FFYLWNJUWAOG', 'LQFOEYORIGIX', 94], 
['YTBRHSVOAFAN', 'OKSGIBWGINWG', 47], ['LBYBYNEZFSWC', 'RYWUXXXUDKFV', 71], ['NVQIRYUAMRPA', 'UMBBRXSEFLFJ', 76], ['YGMKAAXWEGDO', 'MGWBEVNKLNDU', 60], ['PJSXEWSUTMWY', 'GQLXDDDJSTZX', 14], 
['PXEWJFZNYFZD', 'OFGIYIPCNZOV', 88], ['XMNNWJFKDNNY', 'OHWWGGUEMLEL', 86], ['YCTAFKDICTYS', 'MYOLGZAUHCSX', 50], ['CHNVVCCZDPMH', 'HWLTUIEGLYVF', 24], ['OTKWBBGJSNPA', 'QBGIVIBVWJMY', 66], 
['QTBOBWNEWWFN', 'JWSSSABAZKUH', 27], ['FTZBRTFCSFDW', 'QZPPBZVFKGND', 22], ['FTZFMYEXLUSI', 'XXZOEGEEWMUV', 4], ['XFLWCIAHWDCS', 'RHLFOMQHJGGT', 56], ['ONMSFTVWORGY', 'QUZXHQBVNHPD', 34], 
['YZNELIDKXOKZ', 'QQGNUMCCVVHX', 51], ['HILZQSLFQLOW', 'EHUKYRQBKXMM', 81], ['UZISCTZBQYJZ', 'LUIEUOCGBHQS', 7], ['CWOSNKCMWGWG', 'XZINXKTIQMHT', 89], ['LLAMJWCBKQLZ', 'LDWVFXHIHOBQ', 9], 
['GCRWLKALQVIV', 'WDUBOLURXDZU', 61], ['FEOCEWYGSVMD', 'YTWRLUKXMTMI', 79], ['JJRBJLLDKQDY', 'CYQHREFHOMUY', 90], ['EPTNQCGMILWR', 'ROBKYNKBRGXC', 57], ['SVJUAEUEWBPH', 'SCNXWJTHOBDS', 11], 
['SFYELCAPXORD', 'JDLWNTAFDKIZ', 81], ['BUIYPSSYTGPL', 'GBICJNPCGAOZ', 18], ['YDZYQEMSQYFT', 'GTPIDZSFVBQW', 15], ['OFLDJCONONTM', 'HHONUZLAVETD', 18], ['RZCPGDJPWWUC', 'HEHYNTNSMPUI', 44], 
['YNKZPLEROAEA', 'KBWRJMTHXXXP', 20], ['SQXVDDSWXKBL', 'XXJHUURDHFRU', 34], ['IXHKUDZRRHQA', 'HWJKXQVHGDKS', 68], ['FAIGFYMXSVZS', 'MSJGYIWHDRIQ', 79], ['RJPVHDDGHHMR', 'SQRYJJGONAVD', 79], 
['MWHNSSVDCSEW', 'CUQKAYHEKWMA', 79], ['TUFKJNHDXNRX', 'EOSTNXSFCHCP', 46], ['GMBZEFVYMBSR', 'XPENZFUZNKAA', 56], ['PPVCPIVDIIDM', 'ZUTZETIFWQXG', 67], ['HESHVGPDLWMR', 'FACCACTUGVTL', 5], 
['TGXYJLAZJUGH', 'UAXDMQSEQMTA', 49], ['AYJJLCHXWVXX', 'OYCSGZZXWPTK', 39]]

results = [r for r in results if r[2] != 31 and r[2] != 69]
print(results)
for r in results:
    r[0] = ''.join(sorted(r[0]))
    r[1] = ''.join(sorted(r[1]))

for i in range(len(results)):
    r = results[i]
    results.append([r[1], r[0], 100 - r[2]])

results = sorted(results, key=lambda x: x[1])
results = sorted(results, key=lambda x: x[0])
results = sorted(results, key=lambda x: x[2], reverse=True)

# print(results)

# [['ADFJJKNQQSVY', 'ABDDFIJNUYYZ', 100], ['BDJKKMOQSTWY', 'DEFHHLQRRVZZ', 100], ['CCIMNOPRUVWX', 'CEEKNOOPVXXY', 100], 
# ['AEEEFNPTVWXY', 'DEFGIJJMSSVW', 99], ['AEFLLLOUUZZZ', 'EIJKLMMMOPSV', 99], ['DFKLLORTUUUZ', 'HHIIJJJPRUWZ', 99], 
# ['EFFHJKKKMNQZ', 'BEGGINPQVVYZ', 98], ['AAEHKKNORVWZ', 'AADKMNOSTUYZ', 97], ['ADFILQTUUWYZ', 'ACEGIJQQRTXZ', 97], 
# ['BBBCFILOOQSV', 'CDDDDFIJKPZZ', 97]]

[['ADFJJKNQQSVY', 'ABDDFIJNUYYZ', 100], ['BDJKKMOQSTWY', 'DEFHHLQRRVZZ', 100], ['CCIMNOPRUVWX', 'CEEKNOOPVXXY', 100], ['AEEEFNPTVWXY', 'DEFGIJJMSSVW', 99], ['AEFLLLOUUZZZ', 'EIJKLMMMOPSV', 99], 
['DFKLLORTUUUZ', 'HHIIJJJPRUWZ', 99], ['EFFHJKKKMNQZ', 'BEGGINPQVVYZ', 98], ['AAEHKKNORVWZ', 'AADKMNOSTUYZ', 97], ['ADFILQTUUWYZ', 'ACEGIJQQRTXZ', 97], ['BBBCFILOOQSV', 'CDDDDFIJKPZZ', 97], 
['CDEFHILPTVWY', 'EFMNNOSTTVVZ', 97], ['HKMNNOPPTVXY', 'EEGGJKMQTTWY', 97], ['ACHIKOQRVVWW', 'AAFFGGMNOTUX', 96], ['BCCEFHLMNRVW', 'BBCFFGMOQQSY', 96], ['EEEGMOUVWXXZ', 'EFFILMSTUXYZ', 96], 
['EFFHHMRSTTVY', 'FFIJMMNOPQUZ', 96], ['FIINNNPQRSVZ', 'AABFGHILLMQU', 96], ['GHHOORRRUWWY', 'BCHIMNQSVVXY', 96], ['AAAEEGHJKNNY', 'ADHKLLPPQQXY', 95], ['AACCCFGLTTUV', 'DEGHHLMPRSVW', 95], 
['ABCFGJKNQRUY', 'FIJJKMNPSVWX', 95], ['BDEEFGINOQWY', 'DIKLNRSTUWXZ', 95], ['CEFHHJNPSUVX', 'AAGIKMNQTUVX', 95], ['AFFGJLNOUWWY', 'EFGIILOOQRXY', 94], ['BBCDIMMQRTVZ', 'CCFFLNOORWXY', 94], 
['DKKKMPRUUUXZ', 'ABCCHKMQTUUZ', 94], ['FGKLLMQRTWZZ', 'ABBGIJKNNTVY', 94], ['ABFGGHIPRSYZ', 'BFHIJMOPRUVY', 93], ['BCEGHILOQSUU', 'BCIJQSTUYZZZ', 93], ['BCGHIMNNPRVW', 'AABEHJLLNOYY', 93], 
['CHKKLNNNOVWZ', 'CFFIKOPWXXYZ', 93], ['DEEEILNNPSTU', 'CFHHHJNOTUVX', 93], ['AAEEFHJKPRVW', 'CIMPQRSTUWXX', 92], ['ADDGJORSUXXZ', 'DFIJKQSWWXXY', 92], ['BCDEGIJJNPUX', 'ACEGGHOOPUXY', 92], 
['HJKKPPQSSTZZ', 'CKMPRSTTUUXX', 92], ['AABHJPQSVYYZ', 'ADEGGLNOPPTZ', 91], ['ABDFHHKKUVWX', 'BCHLMNPQWYZZ', 91], ['ADGJLOOOTUUY', 'ABCDDEHHOORZ', 91], ['ADGNOORSSWWY', 'FJJKKKLRRWWX', 91], 
['BDEEHHJPRTUY', 'ACFFOQRTUUWY', 91], ['BDFHHILOQVWX', 'ABCJKLLLMQWZ', 91], ['BHIJLOOSSUWW', 'AABCCEFFLOPZ', 91], ['EHHIMPSUVWWX', 'ABBDFJKMQRXZ', 91], ['EHIKORTTVWXX', 'CFFGGIJLMWWY', 91], 
['ACFFHJJKMRTZ', 'ADEEIIOOOQRR', 90], ['BCDDFHOPRVYY', 'ADFIIKPUXYZZ', 90], ['BDDJJJKLLQRY', 'CEFHHMOQRUYY', 90], ['BDLLNNORRUYZ', 'CEGGJLQSUXYZ', 90], ['BCCEEGGJLRRV', 'DOPPQRTTXYYZ', 89], 
['BCDHJNOSSTWX', 'ABEEHJPSUUVW', 89], ['CCDDEJNPRTUY', 'BDIMPQQRRUVZ', 89], ['CCGGKMNOSWWW', 'HIIKMNQTTXXZ', 89], ['ABCDENPTVYYZ', 'AGIJKKPSSTVW', 88], ['ADFMNPSUUVWX', 'DFFLMMPRTUVZ', 88], 
['BDDFGILMNOTY', 'FKLNOOOQQSSX', 88], ['BEINNQSXXYZZ', 'AJJKLMNVVWXY', 88], ['BFGMMTWWXXXZ', 'DFFMOOQUVWXZ', 88], ['CDFFGGGHKRWZ', 'CDFIJKSSSTTU', 88], ['CDGJOTUVXXZZ', 'BCFGNQSTUUVV', 88], 
['CDJLNOQRTTUX', 'GHJLPRRUWYZZ', 88], ['CIJKKNNTXXYZ', 'BDEFGIJKORWZ', 88], ['DEFFJNPWXYZZ', 'CFGIINOOPVYZ', 88], ['EFFKPVWWXXZZ', 'ABGMSUVVVWZZ', 88], ['ADEMNOPPQRVZ', 'BGJJPRTUVWXZ', 87], 
['AELLPPRRVWYY', 'ABDGJQRSSWXZ', 87], ['BDELMMMQQSUY', 'AFFGHIPQSSVZ', 87], ['CDKKLNPQTXYZ', 'CEEEJMNOQSVW', 87], ['AADGMOPRUVXZ', 'ADJKNOQTUVYZ', 86], ['AAFGLQQRTVVV', 'CFFIKNPSWXYZ', 86], 
['ACGHHLPRUWWX', 'ABBEFJKRSTUZ', 86], ['CDDEMNPRSTVW', 'AEFGINNOOPRZ', 86], ['CDEGNPQRRUYZ', 'DDKKKMQRTVVW', 86], ['CEHILLNOPUWX', 'ACHJJOPPQQRY', 86], ['DDDGJLQSTXXZ', 'EJMPSSTUWWXY', 86], 
['DFJKMNNNNWXY', 'EEGGHLLMOUWW', 86], ['ABDJLMNOTYYZ', 'DFGLNOQTUUWY', 85], ['ACCFHMQQSSWZ', 'EEGKMPUVXYYZ', 85], ['BDFGIPQSTVWZ', 'DEFMQQSTYYYZ', 85], ['BEFIJJLMNPXX', 'CFJLOOPPPPUZ', 85], 
['ACEMMPPUXXXY', 'DEJKMOQSTUXY', 84], ['BJKLOOVVXXZZ', 'FFJKKLNOORSV', 84], ['DHJKMMNTTUUV', 'DEFIJLPTUVWZ', 84], ['EFFJLOOSTUYZ', 'FFFGHLMOOTXX', 84], ['GILMOORRSTUX', 'CILNORSSUVWX', 84], 
['AABBEHIJLMTY', 'BBCGLOPPQTUX', 83], ['AACCHLMNPSTV', 'CCCGJKMQRSVZ', 83], ['ABGILNOPQRRX', 'ABCKOSUXYYZZ', 83], ['ACHIJKMNUYZZ', 'AACDMOPSUUWY', 83], ['CDEHIKPQTWZZ', 'CEFGGHILPQST', 83], 
['CGJNOOPPPPXY', 'DDJMMOSSTUWY', 83], ['HHHHILNOPSVW', 'AGNOQQRRTXXZ', 83], ['ABBEIKOPUYZZ', 'CCDDHIKPVXYZ', 82], ['ABCCEFHILLMP', 'EIJPPSSUVWWZ', 82], ['ABCCGGIJNOPZ', 'BGILPPSSTUYY', 82], 
['ADEHHLNOTUVZ', 'CDFJLMNNOOOT', 82], ['AGGGJJNPSUUU', 'CCHHJKLMOPVZ', 82], ['BDDEJJRSUUWY', 'LLMOPSWWWWXY', 82], ['HIJLOQWWXYZZ', 'EIILPQTXXYZZ', 82], ['ACDEFLOPRSXY', 'ADDFIJKLNTWZ', 81], 
['AGGKMNUWWYZZ', 'BBBCFGHIKOUU', 81], ['AGIJMNOSWXXY', 'AEFIIJKOUXYZ', 81], ['BBFGHJJNORSU', 'BDFIMNOPQTTX', 81], ['EFGIKMMNVYYY', 'AADHIIJMOUUZ', 81], ['FHILLLOQQSWZ', 'BEHKKMMQRUXY', 81], 
['ABDDEIMQRRSY', 'BDDLMNOQRVVZ', 80], ['ACCFGIIKMRRZ', 'DEFHHPPQRRSX', 80], ['AEHKNRUWXXYY', 'CFGMTUVWWXYY', 80], ['BBBBDGIKLRRY', 'AACEFIMMMSTZ', 80], ['BCCEELOORUWZ', 'CCDFGIKOQTVX', 80], 
['BHJKMPRTWXXX', 'AAEEKLNOPRYZ', 80], ['CEIJJKKOPPRW', 'ADEFHIKRTXXX', 80], ['DFFGHKKMTUZZ', 'BCDEEFHHKQRR', 80], ['EGIJKMOOPPRV', 'ACEGHKLNRUVY', 80], ['EGJLOOQQSSTZ', 'BKMNOUVVWWZZ', 80], 
['AABDJJKNOPWY', 'DFLLOQTTUUUV', 79], ['AFFGIMSSVXYZ', 'DGHIIJMQRSWY', 79], ['BBDEGLPTUVYZ', 'ABCEEIJPPRXZ', 79], ['CCEJRRVWXXYZ', 'ABCDEEKOQSUX', 79], ['CDEEFGMOSVWY', 'IKLMMRTTUWXY', 79], 
['CDEHMNSSSVWW', 'AACEHKKMQUWY', 79], ['CDFHJLNPTXYY', 'ABGGIJRRWXZZ', 79], ['DDGHHHJMPRRV', 'ADGJJNOQRSVY', 79], ['EGGJJNQRVXYY', 'BJJLMNNQWXYZ', 79], ['JJKLNNRUVWXZ', 'FGGORSTTUVZZ', 79], 
['ACDGHHJMMUWX', 'BEHPPQQRTVWX', 78], ['BDFGKNPPQVZZ', 'BCDFFFRSTTWZ', 78], ['BEFJOPRRXXXZ', 'CCFPQQQQUVYY', 78], ['DFJKKKMQTWWX', 'BCDFFGIILOPT', 78], ['AAABGIKNRTXX', 'BCEHNSSTUUZZ', 77], 
['ABDDHIIIJJLT', 'CCHHMMOPQSSZ', 77], ['AGHKLLMNPRVZ', 'DFGHHJMOUVWZ', 77], ['BDFGGJNQRSSU', 'BDFIJJPPSSVW', 77], ['EGJJLNNOORTW', 'ACDFGGLSSUYZ', 77], ['AAIMNPQRRUVY', 'BBEFFJLMRSUX', 76], 
['ABCELMPPPTVX', 'BFFHHHMQSTXZ', 76], ['ABFIPPSSUZZZ', 'BEFJKTTTXXXZ', 76], ['ADFINOPPRSVW', 'ABBFMNNOORTW', 76], ['BBGJLNNSUUWZ', 'CFJLORRUWWXX', 76], ['BCMNPQQRVYYY', 'AABCDEKLOOSY', 76], 
['CDJLMNNOPQQX', 'EEFGIIOOPUWY', 76], ['DHMPQQTUWWWY', 'ABFGKLRSTTVV', 76], ['EFGHILLTUVWY', 'CCCDHHMNPVVZ', 76], ['AABFFPQRTXYZ', 'AAFGHJKLMVVZ', 75], ['AADEFFHLNSWX', 'GJMNNQSTVVVZ', 75], 
['AEFGHIIMRWWX', 'CDEEGQRSUWXZ', 75], ['BCFGHLMNNOPZ', 'EKLNSUUVWYZZ', 75], ['CDHIJLQRUUVY', 'FHJKLMNOQTUX', 75], ['DEEHIKLNRRST', 'AGIINQQRRSTY', 75], ['ABCCCEILOPWZ', 'CCCHIMRTWWWY', 74], 
['ABJMNOPQSTXY', 'BHIILOOQVVYZ', 74], ['ACFFGKPPQTVV', 'ABDGKLMORRSZ', 74], ['ADGGHJKLPQSW', 'ACDDFHIJLNQX', 74], ['ADGJJKKKMNPX', 'FGMNNPQVWWWX', 74], ['AHKMMMPSTTUU', 'CDFFGMOORWWY', 74], 
['BDIJJPPPSUWX', 'CFFIIKRSUUUZ', 74], ['BGJJLMOOOSUX', 'AEGIMPQSUUVW', 74], ['AABHJKSSSUWZ', 'BBEFNNOQTWWW', 73], ['ACDFHLMMOQRR', 'ABDEGGKKSSUV', 73], ['ADEJKKLMRSTX', 'ABBDGIKKKNPX', 73], 
['CEFKOQRRSSTU', 'BDEEFHLOPTWZ', 73], ['CEJKLMPSUUXY', 'ABCEGJOSVWZZ', 73], ['FJJLLOQTXYYZ', 'ACEFLLLOOSSV', 73], ['BDHILMQUUVWY', 'EFFFKMOPSTTZ', 72], ['EHIIJPQWWXXY', 'EFHIKNNORSTV', 72], 
['ABBHKLOOPPRS', 'AAEHHNNOPVVW', 71], ['ABDEHJJMMOPY', 'EJNQTTUUVWYZ', 71], ['ACDFFGJOPTXY', 'ABCDEHHLOOSW', 71], ['AGIILLMSWWXY', 'CDFHHIKLPPQY', 71], ['BBCEFLNSWYYZ', 'DFKRUUVWXXXY', 71], 
['DHJMMNOPPQXY', 'AABFILOUUVWY', 71], ['AGHIIJKNOQRS', 'EFGILMMPQRSU', 70], ['BEHIJJMQRTXZ', 'CDFGHIIKLLTY', 70], ['BGHIKKOOUWWY', 'DGHILMMNOPQR', 70], ['CDEHHHIMNRUY', 'FLMMOOPVWXYY', 70], 
['EFGHJKOQSVXZ', 'AGGHKKMNPRUV', 70], ['AAAJJJJPRRVZ', 'CDDHIMNTYYYZ', 68], 
['ABBDHPRTTWXX', 'ADDHHINNQRRW', 68], ['ADEHILOOOQSW', 'EGJLLLPRSTUW', 68], ['ADHHIKQRRUXZ', 'DGHHJKKQSVWX', 68], ['DFGIIKLRSWXZ', 'BDDFGOQSTTUY', 68], ['AIIMMMPQRUWY', 'ABCGKKLNPQSU', 67], 
['BCDHHJKNPUWZ', 'BEGHLORUVWZZ', 67], ['CDDIIIMPPPVV', 'EFGIQTTUWXZZ', 67], ['DEGJLNNRSTYY', 'FIIIMQQQRSTZ', 67], ['ABBGJKNOPSTW', 'BBGIIJMQVVWY', 66], ['BDHHNPQQUVXZ', 'FGMNOORSTVWY', 66], 
['BIJJLQRVYZZZ', 'BCDFHHLRRRSY', 66], ['CEEKORRTVVYZ', 'DGHHHMMORSVW', 66], ['DFHHJRRUUUXX', 'BDDKLQSSVWXX', 66], ['DIJJLMOQTVWY', 'AEFFIILORRYY', 66], ['EFIIKLMPPPXY', 'DEEEHNRSUVWY', 66], 
['EGLOPRRRUXYZ', 'CGIJKOPPSUXY', 66], ['FHIKKLLNSUVZ', 'AEFFILMOQSWX', 66], ['AACDEFHHJSSV', 'BFHJJKLLMNUX', 65], ['AADFFJLLQTUV', 'EEFGOOPQSSUY', 65], ['CCFFOPRUUUWZ', 'CCIJLLMNQUXZ', 65], 
['GIJOOPRUUWYY', 'IKKKLMRSTUVV', 65], ['AADFIKLTVZZZ', 'ABDFFKMSTUUV', 64], ['ABCFHQRRSWXX', 'AABDGIJMQWXX', 64], ['ADGIPPQRSVZZ', 'EEGIIJJKMSVV', 64], ['ADLMPQRSTVWY', 'GGHJJJNQRTVY', 64], 
['BBCEGIJNOUZZ', 'JKKKMNOQRXZZ', 64], ['CEFGHIIIIWXY', 'ABFLOPSTTUWY', 64], ['CEFLPQSTUWXX', 'FMNPSTVVXXYY', 64], ['EFFLNNPPQQSZ', 'AAJLMMOQVVYZ', 64], ['FFHMNOQTUWXY', 'DGIIJKRRSUVZ', 64], 
['AAFIIMMOPUWY', 'CDFJMNRUVVXZ', 63], ['ABBCEHORVYYZ', 'DHHIKMSSUVVX', 63], ['ABCFGLLLSUVZ', 'ADEGMMRSTYYZ', 63], ['CEEHJKLORWWZ', 'AADGJOQRTTWW', 63], ['CGJLNNPQRUUY', 'BEGHIORUWXYZ', 63], 
['DIJKLQSSTVXZ', 'EEEFKSTUUVVX', 63], ['HIJKNOPQUVWZ', 'BCEJKKMRRTUV', 63], ['ABJLLPPRTTVX', 'ELLMPPSTVXZZ', 62], ['ADEFJLSUUXXZ', 'ABBDEGJKOVVW', 62], ['BCGHHKMPQQSV', 'AABCFFFIKPRZ', 62], 
['CDGJJLMOOPQQ', 'ABDIIJJLNPRW', 62], ['DDEFFLMPRRWY', 'FHHJKNNRRTUY', 62], ['DEFJLRSUVWWZ', 'CDEFFLNOORUW', 62], ['ACCDDIJKLNVY', 'DGGHHMPQRZZZ', 61], ['ACGIKLLQRVVW', 'BDDLORUUUWXZ', 61], 
['BCCDPPQSSUXZ', 'EGHKLPQQQTUY', 61], ['BCCEJKKOQRTY', 'ACCDGHHIPSTT', 61], ['BEEGKNOOQTUX', 'ABCIIJQTUXYY', 61], ['BFIJLNNRTVXZ', 'CDDDEFOPPQRT', 61], ['CGKOPSTWXYZZ', 'ACHJJLVWXXXY', 61], 
['DEFHMORSTTZZ', 'DEFJKNPSVWXZ', 61], ['DKKLMPPRVWXX', 'FGGHHKOQSTVY', 61], ['AADEGGKMOWXY', 'BDEGKLMNNUVW', 60], ['ABBFGJMRRTZZ', 'BCEEGNOPQUVY', 60], ['ABDFFMNQRTUX', 'AABCFKKRRSTX', 60], 
['ADEGNRSSTVYZ', 'BDDEGJOPQWZZ', 60], ['ADGIKKLNQQWW', 'CCDFFFFGHRSU', 60], ['BCDGIJJLMRSU', 'BBFHINOPPQVZ', 60], ['BEFGJLOOPQRX', 'AIJKLNQTWXYZ', 60], ['DDEFFJLNTUVX', 'AEEMNOSUUWXY', 60], 
['FKKMNPQSWYYZ', 'BBFGMNORSTUY', 60], ['ACCDFGIKMNOU', 'ABEKOOPRRSTU', 59], ['ACCJMNNQRUWZ', 'BFHHIIPQUUYY', 59], ['BBMNPRSTTUYZ', 'ADIIKKMRTWYZ', 59], ['BEFFFOQRUYYZ', 'BGHJLOPPQWWZ', 59], 
['CCEFJRSSXXXY', 'BFJKKMORWWXZ', 59], ['DEFGNOSUVVVZ', 'ACEJJKKKTVYZ', 59], ['ABCHLMQQSUVY', 'IKMNNQTUVWYY', 58], ['ACDEKKLMMVXY', 'BCDFINPQTTVW', 58], ['EIJLMPPRRSTV', 'CCFJKNNNQRVZ', 58], 
['FFKLMOPPRSUZ', 'CFHJLNPQRTTT', 58], ['ACFHIPPRTVXX', 'EHJLMOQTUWZZ', 57], ['BDGGHHMMNOSS', 'ABFHMNNOPTUW', 57], ['BFFFOQRTTUWX', 'ABBGKMNOQUWZ', 57], ['CEGILMNPQRTW', 'BBCGKKNORRXY', 57], 
['AACDDEKLOQTU', 'ABCIJQSTTTYY', 56], ['AACDHIJMTTYZ', 'FGGGLLMOOPTT', 56], ['ABEFJLMNQSUY', 'DDFGLMPSSTWW', 56], ['ACCDFHILSWWX', 'FGGHHJLMOQRT', 56], ['ACEOQSSTUWWZ', 'ABDEGHQSSVWZ', 56], 
['ACHJOQTTUVXZ', 'CDIJKMOSTUVX', 56], ['ADHLRSSTXYYZ', 'CCDEJKMSTXYZ', 56], ['BBDEIPRTTUVY', 'BCEHJKMNPSVV', 56], ['BBEFGMMRSVYZ', 'AAEFKNNPUXZZ', 56], ['BCEGHKNRUWYY', 'FGIIMOOVWWYZ', 56], 
['BEEKOPQRTVYZ', 'CDGJJMPUUWYY', 56], ['BEGHIIJSVVXX', 'ABCFKKOQRWXZ', 56], ['EEEFFHMQQQWY', 'HIKKNNRSTWZZ', 56], ['EHHIMNNPSTUY', 'CCDGJPPRUWWZ', 56], ['IJKOQTUUVWXY', 'GHNOPPSSTWXZ', 56], 
['ABDDGHHKPSVY', 'BCCDGLMOOPVW', 55], ['ACHIIJKLQTUV', 'LMMMNOOQQUVY', 55], ['CCFGHINPRUUV', 'EJMQRTTUUVWX', 55], ['CJJMNNOPWZZZ', 'ABCCEFLORRTT', 55], ['HIIIKLMRUWWY', 'AABCHKMQTTVZ', 55], 
['ACOOPQQSTTWY', 'AABGHHIIKOSU', 54], ['BCCHJKPPSWYZ', 'BCFGHHIKMRST', 54], ['BCDEFHNOOSUW', 'ABEEIJJKMPVX', 54], ['CCEFHNOPSSTX', 'DFHJKNNRTUXX', 54], ['DEFIIKKMNPUU', 'ABDEGHLMRUXZ', 54], 
['ACCDKKLMMQSX', 'AEEGLNOPQSVX', 53], ['ACEKPPPUUVWZ', 'CDDDGHMNUVWY', 53], ['ADDGJLMMOUWY', 'ACGHINQSSWYZ', 53], ['AEEEFFJKMWXX', 'CCCEILMMNQRX', 53], ['BBBFLNQRTWXY', 'HHHLPPQQTTWZ', 53], 
['BGGGIIKNOSWW', 'AABFHNORSTVY', 53], ['DGIIJJJKLTUW', 'DDGHIJNQTUXY', 53], ['ACCEFGJLTXZZ', 'ABDGJNNQSWXZ', 52], ['ADFIKLLRUWYZ', 'CGHIIJKLLMRS', 52], ['CCEFGKOPTWWY', 'EFHIKLMOPQRZ', 52], 
['CDEKKKQVXXZZ', 'CCCFFGGHLMNV', 52], ['AADEMMQQSTUX', 'AGGHJJLTUXYZ', 51], ['ACCHMOOOPSUV', 'BCDDFKNSYYYZ', 51], ['BCDNNPQTUXYZ', 'DEJJLMPRSWWW', 51], ['BCEGHHIIPQTY', 'FHMNOOQQSVWX', 51], 
['CEGJMMNOTUXY', 'DEGIKMOQSUUX', 51], ['DEIKKLNOXYZZ', 'CCGHMNQQUVVX', 51], ['EFGLOQRRTTVW', 'AABEEJLOSTVW', 51], ['EHHIILMMRSYZ', 'HIIKLQSSSXYZ', 51], ['ACCDFIKSTTYY', 'ACGHLMOSUXYZ', 50], 
['ACGHLMOSUXYZ', 'ACCDFIKSTTYY', 50], ['AABEEJLOSTVW', 'EFGLOQRRTTVW', 49], ['AGGHJJLTUXYZ', 'AADEMMQQSTUX', 49], ['BCDDFKNSYYYZ', 'ACCHMOOOPSUV', 49], ['CCGHMNQQUVVX', 'DEIKKLNOXYZZ', 49], 
['DEGIKMOQSUUX', 'CEGJMMNOTUXY', 49], ['DEJJLMPRSWWW', 'BCDNNPQTUXYZ', 49], ['FHMNOOQQSVWX', 'BCEGHHIIPQTY', 49], ['HIIKLQSSSXYZ', 'EHHIILMMRSYZ', 49], ['ABDGJNNQSWXZ', 'ACCEFGJLTXZZ', 48], 
['CCCFFGGHLMNV', 'CDEKKKQVXXZZ', 48], ['CGHIIJKLLMRS', 'ADFIKLLRUWYZ', 48], ['EFHIKLMOPQRZ', 'CCEFGKOPTWWY', 48], ['AABFHNORSTVY', 'BGGGIIKNOSWW', 47], ['ACGHINQSSWYZ', 'ADDGJLMMOUWY', 47], 
['AEEGLNOPQSVX', 'ACCDKKLMMQSX', 47], ['CCCEILMMNQRX', 'AEEEFFJKMWXX', 47], ['CDDDGHMNUVWY', 'ACEKPPPUUVWZ', 47], ['DDGHIJNQTUXY', 'DGIIJJJKLTUW', 47], ['HHHLPPQQTTWZ', 'BBBFLNQRTWXY', 47], 
['AABGHHIIKOSU', 'ACOOPQQSTTWY', 46], ['ABDEGHLMRUXZ', 'DEFIIKKMNPUU', 46], ['ABEEIJJKMPVX', 'BCDEFHNOOSUW', 46], ['BCFGHHIKMRST', 'BCCHJKPPSWYZ', 46], ['DFHJKNNRTUXX', 'CCEFHNOPSSTX', 46], 
['AABCHKMQTTVZ', 'HIIIKLMRUWWY', 45], ['ABCCEFLORRTT', 'CJJMNNOPWZZZ', 45], ['BCCDGLMOOPVW', 'ABDDGHHKPSVY', 45], ['EJMQRTTUUVWX', 'CCFGHINPRUUV', 45], ['LMMMNOOQQUVY', 'ACHIIJKLQTUV', 45], 
['AAEFKNNPUXZZ', 'BBEFGMMRSVYZ', 44], ['ABCFKKOQRWXZ', 'BEGHIIJSVVXX', 44], ['ABCIJQSTTTYY', 'AACDDEKLOQTU', 44], ['ABDEGHQSSVWZ', 'ACEOQSSTUWWZ', 44], ['BCEHJKMNPSVV', 'BBDEIPRTTUVY', 44], 
['CCDEJKMSTXYZ', 'ADHLRSSTXYYZ', 44], ['CCDGJPPRUWWZ', 'EHHIMNNPSTUY', 44], ['CDGJJMPUUWYY', 'BEEKOPQRTVYZ', 44], ['CDIJKMOSTUVX', 'ACHJOQTTUVXZ', 44], ['DDFGLMPSSTWW', 'ABEFJLMNQSUY', 44], 
['FGGGLLMOOPTT', 'AACDHIJMTTYZ', 44], ['FGGHHJLMOQRT', 'ACCDFHILSWWX', 44], ['FGIIMOOVWWYZ', 'BCEGHKNRUWYY', 44], ['GHNOPPSSTWXZ', 'IJKOQTUUVWXY', 44], ['HIKKNNRSTWZZ', 'EEEFFHMQQQWY', 44], 
['ABBGKMNOQUWZ', 'BFFFOQRTTUWX', 43], ['ABFHMNNOPTUW', 'BDGGHHMMNOSS', 43], ['BBCGKKNORRXY', 'CEGILMNPQRTW', 43], ['EHJLMOQTUWZZ', 'ACFHIPPRTVXX', 43], ['BCDFINPQTTVW', 'ACDEKKLMMVXY', 42], 
['CCFJKNNNQRVZ', 'EIJLMPPRRSTV', 42], ['CFHJLNPQRTTT', 'FFKLMOPPRSUZ', 42], ['IKMNNQTUVWYY', 'ABCHLMQQSUVY', 42], ['ABEKOOPRRSTU', 'ACCDFGIKMNOU', 41], ['ACEJJKKKTVYZ', 'DEFGNOSUVVVZ', 41], 
['ADIIKKMRTWYZ', 'BBMNPRSTTUYZ', 41], ['BFHHIIPQUUYY', 'ACCJMNNQRUWZ', 41], ['BFJKKMORWWXZ', 'CCEFJRSSXXXY', 41], ['BGHJLOPPQWWZ', 'BEFFFOQRUYYZ', 41], ['AABCFKKRRSTX', 'ABDFFMNQRTUX', 40], 
['AEEMNOSUUWXY', 'DDEFFJLNTUVX', 40], ['AIJKLNQTWXYZ', 'BEFGJLOOPQRX', 40], ['BBFGMNORSTUY', 'FKKMNPQSWYYZ', 40], ['BBFHINOPPQVZ', 'BCDGIJJLMRSU', 40], ['BCEEGNOPQUVY', 'ABBFGJMRRTZZ', 40], 
['BDDEGJOPQWZZ', 'ADEGNRSSTVYZ', 40], ['BDEGKLMNNUVW', 'AADEGGKMOWXY', 40], ['CCDFFFFGHRSU', 'ADGIKKLNQQWW', 40], ['ABCIIJQTUXYY', 'BEEGKNOOQTUX', 39], ['ACCDGHHIPSTT', 'BCCEJKKOQRTY', 39], 
['ACHJJLVWXXXY', 'CGKOPSTWXYZZ', 39], ['BDDLORUUUWXZ', 'ACGIKLLQRVVW', 39], ['CDDDEFOPPQRT', 'BFIJLNNRTVXZ', 39], ['DEFJKNPSVWXZ', 'DEFHMORSTTZZ', 39], ['DGGHHMPQRZZZ', 'ACCDDIJKLNVY', 39], 
['EGHKLPQQQTUY', 'BCCDPPQSSUXZ', 39], ['FGGHHKOQSTVY', 'DKKLMPPRVWXX', 39], ['AABCFFFIKPRZ', 'BCGHHKMPQQSV', 38], ['ABBDEGJKOVVW', 'ADEFJLSUUXXZ', 38], ['ABDIIJJLNPRW', 'CDGJJLMOOPQQ', 38], 
['CDEFFLNOORUW', 'DEFJLRSUVWWZ', 38], ['ELLMPPSTVXZZ', 'ABJLLPPRTTVX', 38], ['FHHJKNNRRTUY', 'DDEFFLMPRRWY', 38], ['AADGJOQRTTWW', 'CEEHJKLORWWZ', 37], ['ADEGMMRSTYYZ', 'ABCFGLLLSUVZ', 37], 
['BCEJKKMRRTUV', 'HIJKNOPQUVWZ', 37], ['BEGHIORUWXYZ', 'CGJLNNPQRUUY', 37], ['CDFJMNRUVVXZ', 'AAFIIMMOPUWY', 37], ['DHHIKMSSUVVX', 'ABBCEHORVYYZ', 37], ['EEEFKSTUUVVX', 'DIJKLQSSTVXZ', 37], 
['AABDGIJMQWXX', 'ABCFHQRRSWXX', 36], ['AAJLMMOQVVYZ', 'EFFLNNPPQQSZ', 36], ['ABDFFKMSTUUV', 'AADFIKLTVZZZ', 36], ['ABFLOPSTTUWY', 'CEFGHIIIIWXY', 36], ['DGIIJKRRSUVZ', 'FFHMNOQTUWXY', 36], 
['EEGIIJJKMSVV', 'ADGIPPQRSVZZ', 36], ['FMNPSTVVXXYY', 'CEFLPQSTUWXX', 36], ['GGHJJJNQRTVY', 'ADLMPQRSTVWY', 36], ['JKKKMNOQRXZZ', 'BBCEGIJNOUZZ', 36], ['BFHJJKLLMNUX', 'AACDEFHHJSSV', 35], 
['CCIJLLMNQUXZ', 'CCFFOPRUUUWZ', 35], ['EEFGOOPQSSUY', 'AADFFJLLQTUV', 35], ['IKKKLMRSTUVV', 'GIJOOPRUUWYY', 35], ['AEFFIILORRYY', 'DIJJLMOQTVWY', 34], ['AEFFILMOQSWX', 'FHIKKLLNSUVZ', 34], 
['BBGIIJMQVVWY', 'ABBGJKNOPSTW', 34], ['BCDFHHLRRRSY', 'BIJJLQRVYZZZ', 34], ['BDDKLQSSVWXX', 'DFHHJRRUUUXX', 34], ['CGIJKOPPSUXY', 'EGLOPRRRUXYZ', 34], ['DEEEHNRSUVWY', 'EFIIKLMPPPXY', 34], 
['DGHHHMMORSVW', 'CEEKORRTVVYZ', 34], ['FGMNOORSTVWY', 'BDHHNPQQUVXZ', 34], ['ABCGKKLNPQSU', 'AIIMMMPQRUWY', 33], ['BEGHLORUVWZZ', 'BCDHHJKNPUWZ', 33], ['EFGIQTTUWXZZ', 'CDDIIIMPPPVV', 33], 
['FIIIMQQQRSTZ', 'DEGJLNNRSTYY', 33], ['ADDHHINNQRRW', 'ABBDHPRTTWXX', 32], ['BDDFGOQSTTUY', 'DFGIIKLRSWXZ', 32], ['CDDHIMNTYYYZ', 'AAAJJJJPRRVZ', 32], ['DGHHJKKQSVWX', 'ADHHIKQRRUXZ', 32], 
['EGJLLLPRSTUW', 'ADEHILOOOQSW', 32], ['AGGHKKMNPRUV', 'EFGHJKOQSVXZ', 30], 
['CDFGHIIKLLTY', 'BEHIJJMQRTXZ', 30], ['DGHILMMNOPQR', 'BGHIKKOOUWWY', 30], ['EFGILMMPQRSU', 'AGHIIJKNOQRS', 30], ['FLMMOOPVWXYY', 'CDEHHHIMNRUY', 30], ['AABFILOUUVWY', 'DHJMMNOPPQXY', 29], 
['AAEHHNNOPVVW', 'ABBHKLOOPPRS', 29], ['ABCDEHHLOOSW', 'ACDFFGJOPTXY', 29], ['CDFHHIKLPPQY', 'AGIILLMSWWXY', 29], ['DFKRUUVWXXXY', 'BBCEFLNSWYYZ', 29], ['EJNQTTUUVWYZ', 'ABDEHJJMMOPY', 29], 
['EFFFKMOPSTTZ', 'BDHILMQUUVWY', 28], ['EFHIKNNORSTV', 'EHIIJPQWWXXY', 28], ['ABBDGIKKKNPX', 'ADEJKKLMRSTX', 27], ['ABCEGJOSVWZZ', 'CEJKLMPSUUXY', 27], ['ABDEGGKKSSUV', 'ACDFHLMMOQRR', 27], 
['ACEFLLLOOSSV', 'FJJLLOQTXYYZ', 27], ['BBEFNNOQTWWW', 'AABHJKSSSUWZ', 27], ['BDEEFHLOPTWZ', 'CEFKOQRRSSTU', 27], ['ABDGKLMORRSZ', 'ACFFGKPPQTVV', 26], ['ACDDFHIJLNQX', 'ADGGHJKLPQSW', 26], 
['AEGIMPQSUUVW', 'BGJJLMOOOSUX', 26], ['BHIILOOQVVYZ', 'ABJMNOPQSTXY', 26], ['CCCHIMRTWWWY', 'ABCCCEILOPWZ', 26], ['CDFFGMOORWWY', 'AHKMMMPSTTUU', 26], ['CFFIIKRSUUUZ', 'BDIJJPPPSUWX', 26], 
['FGMNNPQVWWWX', 'ADGJJKKKMNPX', 26], ['AAFGHJKLMVVZ', 'AABFFPQRTXYZ', 25], ['AGIINQQRRSTY', 'DEEHIKLNRRST', 25], ['CDEEGQRSUWXZ', 'AEFGHIIMRWWX', 25], ['EKLNSUUVWYZZ', 'BCFGHLMNNOPZ', 25], 
['FHJKLMNOQTUX', 'CDHIJLQRUUVY', 25], ['GJMNNQSTVVVZ', 'AADEFFHLNSWX', 25], ['AABCDEKLOOSY', 'BCMNPQQRVYYY', 24], ['ABBFMNNOORTW', 'ADFINOPPRSVW', 24], ['ABFGKLRSTTVV', 'DHMPQQTUWWWY', 24], 
['BBEFFJLMRSUX', 'AAIMNPQRRUVY', 24], ['BEFJKTTTXXXZ', 'ABFIPPSSUZZZ', 24], ['BFFHHHMQSTXZ', 'ABCELMPPPTVX', 24], ['CCCDHHMNPVVZ', 'EFGHILLTUVWY', 24], ['CFJLORRUWWXX', 'BBGJLNNSUUWZ', 24], 
['EEFGIIOOPUWY', 'CDJLMNNOPQQX', 24], ['ACDFGGLSSUYZ', 'EGJJLNNOORTW', 23], ['BCEHNSSTUUZZ', 'AAABGIKNRTXX', 23], ['BDFIJJPPSSVW', 'BDFGGJNQRSSU', 23], ['CCHHMMOPQSSZ', 'ABDDHIIIJJLT', 23], 
['DFGHHJMOUVWZ', 'AGHKLLMNPRVZ', 23], ['BCDFFFRSTTWZ', 'BDFGKNPPQVZZ', 22], ['BCDFFGIILOPT', 'DFJKKKMQTWWX', 22], ['BEHPPQQRTVWX', 'ACDGHHJMMUWX', 22], ['CCFPQQQQUVYY', 'BEFJOPRRXXXZ', 22], 
['AACEHKKMQUWY', 'CDEHMNSSSVWW', 21], ['ABCDEEKOQSUX', 'CCEJRRVWXXYZ', 21], ['ABCEEIJPPRXZ', 'BBDEGLPTUVYZ', 21], ['ABGGIJRRWXZZ', 'CDFHJLNPTXYY', 21], ['ADGJJNOQRSVY', 'DDGHHHJMPRRV', 21], 
['BJJLMNNQWXYZ', 'EGGJJNQRVXYY', 21], ['DFLLOQTTUUUV', 'AABDJJKNOPWY', 21], ['DGHIIJMQRSWY', 'AFFGIMSSVXYZ', 21], ['FGGORSTTUVZZ', 'JJKLNNRUVWXZ', 21], ['IKLMMRTTUWXY', 'CDEEFGMOSVWY', 21], 
['AACEFIMMMSTZ', 'BBBBDGIKLRRY', 20], ['AAEEKLNOPRYZ', 'BHJKMPRTWXXX', 20], ['ACEGHKLNRUVY', 'EGIJKMOOPPRV', 20], ['ADEFHIKRTXXX', 'CEIJJKKOPPRW', 20], ['BCDEEFHHKQRR', 'DFFGHKKMTUZZ', 20], 
['BDDLMNOQRVVZ', 'ABDDEIMQRRSY', 20], ['BKMNOUVVWWZZ', 'EGJLOOQQSSTZ', 20], ['CCDFGIKOQTVX', 'BCCEELOORUWZ', 20], ['CFGMTUVWWXYY', 'AEHKNRUWXXYY', 20], ['DEFHHPPQRRSX', 'ACCFGIIKMRRZ', 20], 
['AADHIIJMOUUZ', 'EFGIKMMNVYYY', 19], ['ADDFIJKLNTWZ', 'ACDEFLOPRSXY', 19], ['AEFIIJKOUXYZ', 'AGIJMNOSWXXY', 19], ['BBBCFGHIKOUU', 'AGGKMNUWWYZZ', 19], ['BDFIMNOPQTTX', 'BBFGHJJNORSU', 19], 
['BEHKKMMQRUXY', 'FHILLLOQQSWZ', 19], ['BGILPPSSTUYY', 'ABCCGGIJNOPZ', 18], ['CCDDHIKPVXYZ', 'ABBEIKOPUYZZ', 18], ['CCHHJKLMOPVZ', 'AGGGJJNPSUUU', 18], ['CDFJLMNNOOOT', 'ADEHHLNOTUVZ', 18], 
['EIILPQTXXYZZ', 'HIJLOQWWXYZZ', 18], ['EIJPPSSUVWWZ', 'ABCCEFHILLMP', 18], ['LLMOPSWWWWXY', 'BDDEJJRSUUWY', 18], ['AACDMOPSUUWY', 'ACHIJKMNUYZZ', 17], ['ABCKOSUXYYZZ', 'ABGILNOPQRRX', 17], 
['AGNOQQRRTXXZ', 'HHHHILNOPSVW', 17], ['BBCGLOPPQTUX', 'AABBEHIJLMTY', 17], ['CCCGJKMQRSVZ', 'AACCHLMNPSTV', 17], ['CEFGGHILPQST', 'CDEHIKPQTWZZ', 17], ['DDJMMOSSTUWY', 'CGJNOOPPPPXY', 17], 
['CILNORSSUVWX', 'GILMOORRSTUX', 16], ['DEFIJLPTUVWZ', 'DHJKMMNTTUUV', 16], ['DEJKMOQSTUXY', 'ACEMMPPUXXXY', 16], ['FFFGHLMOOTXX', 'EFFJLOOSTUYZ', 16], ['FFJKKLNOORSV', 'BJKLOOVVXXZZ', 16], 
['CFJLOOPPPPUZ', 'BEFIJJLMNPXX', 15], ['DEFMQQSTYYYZ', 'BDFGIPQSTVWZ', 15], ['DFGLNOQTUUWY', 'ABDJLMNOTYYZ', 15], ['EEGKMPUVXYYZ', 'ACCFHMQQSSWZ', 15], ['ABBEFJKRSTUZ', 'ACGHHLPRUWWX', 14], 
['ACHJJOPPQQRY', 'CEHILLNOPUWX', 14], ['ADJKNOQTUVYZ', 'AADGMOPRUVXZ', 14], ['AEFGINNOOPRZ', 'CDDEMNPRSTVW', 14], ['CFFIKNPSWXYZ', 'AAFGLQQRTVVV', 14], ['DDKKKMQRTVVW', 'CDEGNPQRRUYZ', 14], 
['EEGGHLLMOUWW', 'DFJKMNNNNWXY', 14], ['EJMPSSTUWWXY', 'DDDGJLQSTXXZ', 14], ['ABDGJQRSSWXZ', 'AELLPPRRVWYY', 13], ['AFFGHIPQSSVZ', 'BDELMMMQQSUY', 13], ['BGJJPRTUVWXZ', 'ADEMNOPPQRVZ', 13], 
['CEEEJMNOQSVW', 'CDKKLNPQTXYZ', 13], ['ABGMSUVVVWZZ', 'EFFKPVWWXXZZ', 12], ['AGIJKKPSSTVW', 'ABCDENPTVYYZ', 12], ['AJJKLMNVVWXY', 'BEINNQSXXYZZ', 12], ['BCFGNQSTUUVV', 'CDGJOTUVXXZZ', 12], 
['BDEFGIJKORWZ', 'CIJKKNNTXXYZ', 12], ['CDFIJKSSSTTU', 'CDFFGGGHKRWZ', 12], ['CFGIINOOPVYZ', 'DEFFJNPWXYZZ', 12], ['DFFLMMPRTUVZ', 'ADFMNPSUUVWX', 12], ['DFFMOOQUVWXZ', 'BFGMMTWWXXXZ', 12], 
['FKLNOOOQQSSX', 'BDDFGILMNOTY', 12], ['GHJLPRRUWYZZ', 'CDJLNOQRTTUX', 12], ['ABEEHJPSUUVW', 'BCDHJNOSSTWX', 11], ['BDIMPQQRRUVZ', 'CCDDEJNPRTUY', 11], ['DOPPQRTTXYYZ', 'BCCEEGGJLRRV', 11], 
['HIIKMNQTTXXZ', 'CCGGKMNOSWWW', 11], ['ADEEIIOOOQRR', 'ACFFHJJKMRTZ', 10], ['ADFIIKPUXYZZ', 'BCDDFHOPRVYY', 10], ['CEFHHMOQRUYY', 'BDDJJJKLLQRY', 10], ['CEGGJLQSUXYZ', 'BDLLNNORRUYZ', 10], 
['AABCCEFFLOPZ', 'BHIJLOOSSUWW', 9], ['ABBDFJKMQRXZ', 'EHHIMPSUVWWX', 9], ['ABCDDEHHOORZ', 'ADGJLOOOTUUY', 9], ['ABCJKLLLMQWZ', 'BDFHHILOQVWX', 9], ['ACFFOQRTUUWY', 'BDEEHHJPRTUY', 9], 
['ADEGGLNOPPTZ', 'AABHJPQSVYYZ', 9], ['BCHLMNPQWYZZ', 'ABDFHHKKUVWX', 9], ['CFFGGIJLMWWY', 'EHIKORTTVWXX', 9], ['FJJKKKLRRWWX', 'ADGNOORSSWWY', 9], ['ACEGGHOOPUXY', 'BCDEGIJJNPUX', 8], 
['CIMPQRSTUWXX', 'AAEEFHJKPRVW', 8], ['CKMPRSTTUUXX', 'HJKKPPQSSTZZ', 8], ['DFIJKQSWWXXY', 'ADDGJORSUXXZ', 8], ['AABEHJLLNOYY', 'BCGHIMNNPRVW', 7], ['BCIJQSTUYZZZ', 'BCEGHILOQSUU', 7], 
['BFHIJMOPRUVY', 'ABFGGHIPRSYZ', 7], ['CFFIKOPWXXYZ', 'CHKKLNNNOVWZ', 7], ['CFHHHJNOTUVX', 'DEEEILNNPSTU', 7], ['ABBGIJKNNTVY', 'FGKLLMQRTWZZ', 6], ['ABCCHKMQTUUZ', 'DKKKMPRUUUXZ', 6], 
['CCFFLNOORWXY', 'BBCDIMMQRTVZ', 6], ['EFGIILOOQRXY', 'AFFGJLNOUWWY', 6], ['AAGIKMNQTUVX', 'CEFHHJNPSUVX', 5], ['ADHKLLPPQQXY', 'AAAEEGHJKNNY', 5], ['DEGHHLMPRSVW', 'AACCCFGLTTUV', 5], 
['DIKLNRSTUWXZ', 'BDEEFGINOQWY', 5], ['FIJJKMNPSVWX', 'ABCFGJKNQRUY', 5], ['AABFGHILLMQU', 'FIINNNPQRSVZ', 4], ['AAFFGGMNOTUX', 'ACHIKOQRVVWW', 4], ['BBCFFGMOQQSY', 'BCCEFHLMNRVW', 4], 
['BCHIMNQSVVXY', 'GHHOORRRUWWY', 4], ['EFFILMSTUXYZ', 'EEEGMOUVWXXZ', 4], ['FFIJMMNOPQUZ', 'EFFHHMRSTTVY', 4], ['AADKMNOSTUYZ', 'AAEHKKNORVWZ', 3], ['ACEGIJQQRTXZ', 'ADFILQTUUWYZ', 3], 
['CDDDDFIJKPZZ', 'BBBCFILOOQSV', 3], ['EEGGJKMQTTWY', 'HKMNNOPPTVXY', 3], ['EFMNNOSTTVVZ', 'CDEFHILPTVWY', 3], ['BEGGINPQVVYZ', 'EFFHJKKKMNQZ', 2], ['DEFGIJJMSSVW', 'AEEEFNPTVWXY', 1], 
['EIJKLMMMOPSV', 'AEFLLLOUUZZZ', 1], ['HHIIJJJPRUWZ', 'DFKLLORTUUUZ', 1], ['ABDDFIJNUYYZ', 'ADFJJKNQQSVY', 0], ['CEEKNOOPVXXY', 'CCIMNOPRUVWX', 0], ['DEFHHLQRRVZZ', 'BDJKKMOQSTWY', 0]]


def optimalRoute(downhillScores, start, finish):
    hillGraph = RevGraph(downhillScores)
    source = hillGraph.vertices[finish]
    if not source:
        return None
    source.profit = 0
    vert_list = deque([source])
    while vert_list:
        u = vert_list.popleft()
        if u.id == start:
            continue
        u.visited = True        # Mark the vertex as visited
        for edge in u.edges:
            v = edge.v
            new_prof = u.profit + edge.w
            if new_prof > v.profit:
                v.profit, v.next = new_prof, u
            if not v.visited:
                vert_list.append(v)
    returning_list, path_vert = [], hillGraph.vertices[start]
    while path_vert:
        returning_list.append(path_vert.id)
        path_vert = path_vert.next
    return returning_list if returning_list[-1] == finish else None
